-- MySQL Script generated by MySQL Workbench
-- Fri Apr 17 03:18:14 2020
-- Model: Modelo PSPC    Version: 1.0

-- Este es el modelo de base de datos para el sistema que utilizara el Proyecto Sector Productivo Cultural.

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mec` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `mec` ;

-- -----------------------------------------------------
-- Table `mec`.`barrios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`barrios` (
  `id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mec`.`calles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`calles` (
  `id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(40) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mec`.`cuadras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`cuadras` (
  `id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mec`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`direcciones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `barrio_id` TINYINT(2) UNSIGNED NULL,
  `chacra` VARCHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL,
  `cuadra_id` TINYINT(2) UNSIGNED NULL,
  `sector` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL,
  `calle_id` TINYINT(3) UNSIGNED NULL,
  `altura` VARCHAR(6) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL,
  `casa` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL,
  `departamento` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL,
  `piso` TINYINT(2) UNSIGNED NULL,
  `codigoPlus` VARCHAR(7) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_direcciones_barrios1_idx` (`barrio_id` ASC),
  INDEX `direcciones_calles` (`calle_id` ASC),
  INDEX `fk_direcciones_cuadras1_idx` (`cuadra_id` ASC),
  CONSTRAINT `fk_direcciones_barrios1`
    FOREIGN KEY (`barrio_id`)
    REFERENCES `mec`.`barrios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `direcciones_calles`
    FOREIGN KEY (`calle_id`)
    REFERENCES `mec`.`calles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direcciones_cuadras1`
    FOREIGN KEY (`cuadra_id`)
    REFERENCES `mec`.`cuadras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mec`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`paises` (
  `id` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(10) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mec`.`provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`provincias` (
  `id` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(18) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `pais_id` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC),
  INDEX `fk_provincias_paises1_idx` (`pais_id` ASC),
  CONSTRAINT `fk_provincias_paises1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `mec`.`paises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mec`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`departamentos` (
  `id` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(18) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `provincia_id` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC),
  INDEX `fk_departamentos_provincias1_idx` (`provincia_id` ASC),
  CONSTRAINT `fk_departamentos_provincias1`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `mec`.`provincias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mec`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`municipios` (
  `id` TINYINT(2) UNSIGNED NOT NULL,
  `descripcion` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `departamento_id` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC),
  INDEX `fk_municipios_departamentos1_idx` (`departamento_id` ASC),
  CONSTRAINT `fk_municipios_departamentos1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `mec`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mec`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`contactos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `direccion_id` INT UNSIGNED NOT NULL,
  `municipio_id` TINYINT(2) UNSIGNED NOT NULL,
  `telefono1` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL,
  `telefono2` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL,
  `correo1` VARCHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL,
  `correo2` VARCHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `direccion_id` (`direccion_id` ASC),
  CONSTRAINT `direccion_id`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `mec`.`direcciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contactos_municipios1`
    FOREIGN KEY (`municipio_id`)
    REFERENCES `mec`.`municipios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mec`.`generos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`generos` (
  `id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC));


-- -----------------------------------------------------
-- Table `mec`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`personas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(120) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `nombre` VARCHAR(120) NOT NULL,
  `nacimiento_id` DATE NOT NULL,
  `estado` TINYINT UNSIGNED NOT NULL,
  `contacto_id` INT UNSIGNED NULL,
  `genero_id` TINYINT(2) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `personas_contactos` (`contacto_id` ASC),
  INDEX `personas_generos` (`genero_id` ASC),
  CONSTRAINT `contacto_id`
    FOREIGN KEY (`contacto_id`)
    REFERENCES `mec`.`contactos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `genero_id`
    FOREIGN KEY (`genero_id`)
    REFERENCES `mec`.`generos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mec`.`dominios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`dominios` (
  `id` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL COMMENT 'Dominios culturales\nEquipamientos y materiales de apoyo de dominios culturales\nDominios transversales\nDominios relacionados\nEquipamientos y materiales de apoyo de dominios relacionados',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC));


-- -----------------------------------------------------
-- Table `mec`.`funciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`funciones` (
  `id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL COMMENT 'Creación\nDifusión\nExhibición/Transmisión\nArchivística/Preservación\nConsumo/Participación\nProducción\nEducación/Capacitación\nProducción, difusión',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC));


-- -----------------------------------------------------
-- Table `mec`.`arreglos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`arreglos` (
  `id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(12) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL COMMENT 'CIIU4, CPC2, SA07, SITC4, CIUO08, ICATUS',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC));


-- -----------------------------------------------------
-- Table `mec`.`ambitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`ambitos` (
  `id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL COMMENT 'Patrimonio Cultural y Natural\nPresentaciones Artísticas y Celebraciones\nArtes Visuales y Artesanías\nLibros y Prensa\nMedios Audiovisuales e Interactivos\nDiseño y Servicios Creativos\nEducación Cultural\nPatrimonio Inmaterial\nTurismo\nDeportes y recreación',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC));


-- -----------------------------------------------------
-- Table `mec`.`denominaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`denominaciones` (
  `id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL COMMENT 'Antigüedades\nInstrumentos musicales\nMedios grabados\nPinturas\nOtras artes visuales\nArtesanías\nJoyas\nFotografía\nLibros\nDiarios\nOtros materiales impresos\nFilmes y videos\n_ _ _ _ _ _ _ _ _\nArquitectura y diseño\nCelebración\nMúsica\nAudiovisuales\nComputadoras y equipamientos relacionados\nDeportes\nDeportes y recreación\nJuegos de azar',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC));


-- -----------------------------------------------------
-- Table `mec`.`subdominios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`subdominios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ambito_id` TINYINT(2) UNSIGNED NOT NULL,
  `dominio_id` TINYINT(1) UNSIGNED NOT NULL,
  `denominacion_id` TINYINT(2) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `ambito_id` (`ambito_id` ASC),
  INDEX `dominio_id` (`dominio_id` ASC),
  INDEX `denominacion_id` (`denominacion_id` ASC),
  CONSTRAINT `subdominios_ambitos`
    FOREIGN KEY (`ambito_id`)
    REFERENCES `mec`.`ambitos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subdominios_dominios`
    FOREIGN KEY (`dominio_id`)
    REFERENCES `mec`.`dominios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subdominios_denominaciones`
    FOREIGN KEY (`denominacion_id`)
    REFERENCES `mec`.`denominaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mec`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`categorias` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(6) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `descripcion` VARCHAR(355) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `nota` VARCHAR(1110) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NULL,
  `arreglo_id` TINYINT(2) UNSIGNED NOT NULL,
  `subdominio_id` INT UNSIGNED NOT NULL,
  `funcion_id` TINYINT(2) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  INDEX `arreglo_id` (`arreglo_id` ASC),
  INDEX `subdominio_id` (`subdominio_id` ASC),
  INDEX `funcion_id` (`funcion_id` ASC),
  CONSTRAINT `categorias_arreglos`
    FOREIGN KEY (`arreglo_id`)
    REFERENCES `mec`.`arreglos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categorias_subdominios`
    FOREIGN KEY (`subdominio_id`)
    REFERENCES `mec`.`subdominios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `categorias_funciones`
    FOREIGN KEY (`funcion_id`)
    REFERENCES `mec`.`funciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mec`.`organizaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`organizaciones` (
  `id` SMALLINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  `contacto_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC),
  INDEX `contacto_id` (`contacto_id` ASC),
  CONSTRAINT `organizaciones_contactos`
    FOREIGN KEY (`contacto_id`)
    REFERENCES `mec`.`contactos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mec`.`clasificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`clasificaciones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `persona_id` INT UNSIGNED NULL,
  `organizacion_id` SMALLINT(3) UNSIGNED NULL,
  `categoria_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `persona_id` (`persona_id` ASC),
  INDEX `organizacion_id` (`organizacion_id` ASC),
  INDEX `categoria_id` (`categoria_id` ASC),
  CONSTRAINT `clasificaciones_personas`
    FOREIGN KEY (`persona_id`)
    REFERENCES `mec`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `clasificaciones_organizaciones`
    FOREIGN KEY (`organizacion_id`)
    REFERENCES `mec`.`organizaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `clasificaciones_categorias`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mec`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mec`.`visitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`visitas` (
  `id` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` TINYINT(1) UNSIGNED NOT NULL COMMENT 'Si es la primer visita, la segunda, tercera, cuarta o quinta.',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mec`.`otros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`otros` (
  `id` TINYINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL COMMENT 'En el caso de la que eleccion sea la\n07 Otros (esp.) ___________________________\nEn este espacio se describira ese otros',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_UNIQUE` (`descripcion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mec`.`resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`resultados` (
  `id` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL COMMENT 'Entrevista completa\nEntrevista incompleta\nEntrevista aplazada\nAusentes temporales\nSe negó a dar información\nInformante inadecuado\nOtros (esp.) ___________________________',
  `otros_id` TINYINT(2) UNSIGNED NULL COMMENT 'En caso de que sea otro, aqui se especifica. este campo puede ser null',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_UNIQUE` (`descripcion` ASC),
  INDEX `otros_id` (`otros_id` ASC),
  CONSTRAINT `resultados_otros`
    FOREIGN KEY (`otros_id`)
    REFERENCES `mec`.`otros` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mec`.`cabeceras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`cabeceras` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_entidad` VARCHAR(45) NOT NULL,
  `visita_id` TINYINT(1) UNSIGNED NOT NULL,
  `fecha` DATE NOT NULL,
  `persona_id` INT UNSIGNED NOT NULL COMMENT 'persona_id son los datos del entrevistador, esto remplaza al campo \'nombre_del_entrevistador\'',
  `hora_inicio` TIME NOT NULL,
  `hora_final` TIME NULL,
  `duracion` TIME NULL,
  `resultado_id` TINYINT(1) UNSIGNED NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `visita_id` (`visita_id` ASC),
  INDEX `resultado_id` (`resultado_id` ASC),
  INDEX `cabeceras_personas_idx` (`persona_id` ASC),
  CONSTRAINT `encuestas_visitas`
    FOREIGN KEY (`visita_id`)
    REFERENCES `mec`.`visitas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `encuestas_resultados`
    FOREIGN KEY (`resultado_id`)
    REFERENCES `mec`.`resultados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cabeceras_personas`
    FOREIGN KEY (`persona_id`)
    REFERENCES `mec`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'file:///E:/cultura/Cuestionario.pdf';


-- -----------------------------------------------------
-- Table `mec`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`preguntas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoria_id` INT UNSIGNED NULL COMMENT 'para acceder a la codificacion de ICATUS que es para las encuestas de uso de tiempo',
  `descripcion` VARCHAR(90) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_id` (`categoria_id` ASC),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC),
  CONSTRAINT `preguntas_categorias`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mec`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mec`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`respuestas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `descripcion_UNIQUE` (`descripcion` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mec`.`encuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mec`.`encuestas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cabecera_id` INT UNSIGNED NOT NULL,
  `pregunta_id` INT UNSIGNED NOT NULL,
  `respuesta_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `encuestas_cabeceras_idx` (`cabecera_id` ASC),
  INDEX `encuestas_preguntas_idx` (`pregunta_id` ASC),
  INDEX `encuestas_respuestas_idx` (`respuesta_id` ASC),
  CONSTRAINT `encuestas_cabeceras`
    FOREIGN KEY (`cabecera_id`)
    REFERENCES `mec`.`cabeceras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `encuestas_preguntas`
    FOREIGN KEY (`pregunta_id`)
    REFERENCES `mec`.`preguntas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `encuestas_respuestas`
    FOREIGN KEY (`respuesta_id`)
    REFERENCES `mec`.`respuestas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
